ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Révoquer les autorisations accordées aux rôles
REVOKE ALL PRIVILEGES ON SCHEMA GLPI_TEST FROM GLPI_PAU_ADMIN;
REVOKE ALL PRIVILEGES ON SCHEMA GLPI_TEST FROM GLPI_PAU_DEV;
REVOKE ALL PRIVILEGES ON SCHEMA GLPI_TEST FROM GLPI_PAU_ANALYST;
REVOKE ALL PRIVILEGES ON SCHEMA GLPI_TEST FROM GLPI_PAU_OBSERVER;

-- Supprimer les rôles
DROP ROLE GLPI_PAU_ADMIN;
DROP ROLE GLPI_PAU_DEV;
DROP ROLE GLPI_PAU_ANALYST;
DROP ROLE GLPI_PAU_OBSERVER;

COMMIT;
exit;
