ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
-- Cr�ation des utilisateurs

-- Création du tablespace et du tablespace temporaire pour GLPI_OBSERVER
CREATE TABLESPACE GLPI_OBSERVER_TS DATAFILE 'C:\TAD\ROLES\GLPI_OBSERVER_TS.dat' SIZE 100M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE GLPI_OBSERVER_TEMP_TS TEMPFILE 'C:\TAD\ROLES\GLPI_OBSERVER_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- Création du tablespace et du tablespace temporaire pour GLPI_ANALYST
CREATE TABLESPACE GLPI_ANALYST_TS DATAFILE 'C:\TAD\ROLES\GLPI_ANALYST_TS.dat' SIZE 100M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE GLPI_ANALYST_TEMP_TS TEMPFILE 'C:\TAD\ROLES\GLPI_ANALYST_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- Création du tablespace et du tablespace temporaire pour GLPI_DEV
CREATE TABLESPACE GLPI_DEV_TS DATAFILE 'C:\TAD\ROLES\GLPI_DEV_TS.dat' SIZE 100M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE GLPI_DEV_TEMP_TS TEMPFILE 'C:\TAD\ROLES\GLPI_DEV_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- Création du tablespace et du tablespace temporaire pour GLPI_ADMIN
CREATE TABLESPACE GLPI_ADMIN_TS DATAFILE 'C:\TAD\ROLES\GLPI_ADMIN_TS.dat' SIZE 100M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE GLPI_ADMIN_TEMP_TS TEMPFILE 'C:\TAD\ROLES\GLPI_ADMIN_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- Utilisateurs GLPI_ADMIN
CREATE USER admin_glpi_1 IDENTIFIED BY psswd_admin_1 DEFAULT TABLESPACE GLPI_ADMIN_TS TEMPORARY TABLESPACE GLPI_ADMIN_TEMP_TS;
CREATE USER admin_glpi_2 IDENTIFIED BY psswd_admin_2 DEFAULT TABLESPACE GLPI_ADMIN_TS TEMPORARY TABLESPACE GLPI_ADMIN_TEMP_TS;

GRANT GLPI_ADMIN TO admin_glpi_1;
GRANT GLPI_ADMIN TO admin_glpi_2;

-- Utilisateurs GLPI_DEV
CREATE USER dev_glpi_1 IDENTIFIED BY psswd_dev_1 DEFAULT TABLESPACE GLPI_DEV_TS TEMPORARY TABLESPACE GLPI_DEV_TEMP_TS;
CREATE USER dev_glpi_2 IDENTIFIED BY psswd_dev_1 DEFAULT TABLESPACE GLPI_DEV_TS TEMPORARY TABLESPACE GLPI_DEV_TEMP_TS;

GRANT GLPI_DEV TO dev_glpi_1;
GRANT GLPI_DEV TO dev_glpi_2;

-- Utilisateurs GLPI_ANALYST
CREATE USER analyst_glpi_1 IDENTIFIED BY psswd_analyst_1 DEFAULT TABLESPACE GLPI_ANALYST_TS TEMPORARY TABLESPACE GLPI_ANALYST_TEMP_TS;
CREATE USER analyst_glpi_2 IDENTIFIED BY psswd_analyst_2 DEFAULT TABLESPACE GLPI_ANALYST_TS TEMPORARY TABLESPACE GLPI_ANALYST_TEMP_TS;

GRANT GLPI_ANALYST TO analyst_glpi_1;
GRANT GLPI_ANALYST TO analyst_glpi_2;

-- Utilisateurs GLPI_OBSERVER
CREATE USER observer_glpi_1 IDENTIFIED BY psswd_observer_1 DEFAULT TABLESPACE GLPI_OBSERVER_TS TEMPORARY TABLESPACE GLPI_OBSERVER_TEMP_TS;
CREATE USER observer_glpi_2 IDENTIFIED BY psswd_observer_2 DEFAULT TABLESPACE GLPI_OBSERVER_TS TEMPORARY TABLESPACE GLPI_OBSERVER_TEMP_TS;

GRANT GLPI_OBSERVER TO observer_glpi_1;
GRANT GLPI_OBSERVER TO observer_glpi_2;
COMMIT;
exit;