ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Supprimer les autorisations accordées aux rôles
REVOKE ALL PRIVILEGES ON SCHEMA GLPI_PROD FROM GLPI_CERGY_ADMIN;
REVOKE ALL PRIVILEGES ON SCHEMA GLPI_PROD FROM GLPI_CERGY_DEV;
REVOKE ALL PRIVILEGES ON SCHEMA GLPI_PROD FROM GLPI_CERGY_ANALYST;
REVOKE ALL PRIVILEGES ON SCHEMA GLPI_PROD FROM GLPI_CERGY_OBSERVER;

-- Supprimer les rôles
DROP ROLE GLPI_CERGY_ADMIN;
DROP ROLE GLPI_CERGY_DEV;
DROP ROLE GLPI_CERGY_ANALYST;
DROP ROLE GLPI_CERGY_OBSERVER;

COMMIT;
exit;
