ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Suppression des tablespaces et des utilisateurs pour GLPI_TEST
DROP USER GLPI_TEST CASCADE;
DROP TABLESPACE GLPI_TEST_TABSPACE INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_TEST_TABSPACE_TEMP INCLUDING CONTENTS AND DATAFILES;

-- Suppression des tablespaces et des utilisateurs pour GLPI_PROD
DROP USER GLPI_PROD CASCADE;
DROP TABLESPACE GLPI_PROD_TABSPACE INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_PROD_TABSPACE_TEMP INCLUDING CONTENTS AND DATAFILES;

-- Suppression des tablespaces pour les rôles GLPI
DROP TABLESPACE GLPI_OBSERVER_TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_OBSERVER_TEMP_TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_ANALYST_TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_ANALYST_TEMP_TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_DEV_TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_DEV_TEMP_TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_ADMIN_TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GLPI_ADMIN_TEMP_TS INCLUDING CONTENTS AND DATAFILES;

COMMIT;
EXIT;
