-- Supprimer la fonction CHECK_VALUE_EXIST de GLPI_CERGY
DROP FUNCTION GLPI_CERGY.CHECK_VALUE_EXIST;

-- Supprimer la fonction GET_ID_WHERE de GLPI_CERGY
DROP FUNCTION GLPI_CERGY.GET_ID_WHERE;

-- Supprimer la fonction GET_TICKET de GLPI_CERGY
DROP FUNCTION GLPI_CERGY.GET_TICKET;

-- Supprimer la procédure GET_USER_TICKETS de GLPI_CERGY
DROP PROCEDURE GLPI_CERGY.GET_USER_TICKETS;

-- Supprimer la procédure GET_TICKET_COMMENTS de GLPI_CERGY
DROP PROCEDURE GLPI_CERGY.GET_TICKET_COMMENTS;

-- Supprimer la procédure SET_TICKET_STATUS de GLPI_CERGY
DROP PROCEDURE GLPI_CERGY.SET_TICKET_STATUS;

-- Supprimer la procédure SOLVE_TICKET de GLPI_CERGY
DROP PROCEDURE GLPI_CERGY.SOLVE_TICKET;

-- Supprimer la procédure CLOSE_TICKET de GLPI_CERGY
DROP PROCEDURE GLPI_CERGY.CLOSE_TICKET;

-- Supprimer la procédure ASSIGN_TICKET_TO_USER de GLPI_CERGY
DROP PROCEDURE GLPI_CERGY.ASSIGN_TICKET_TO_USER;

-- Supprimer la procédure REFRESH_MATERIALIZED_VIEW de GLPI_CERGY
DROP PROCEDURE GLPI_CERGY.REFRESH_MATERIALIZED_VIEW;


-- Supprimer la fonction CHECK_VALUE_EXIST de GLPI_PAU
DROP FUNCTION GLPI_PAU.CHECK_VALUE_EXIST;

-- Supprimer la fonction GET_ID_WHERE de GLPI_PAU
DROP FUNCTION GLPI_PAU.GET_ID_WHERE;

-- Supprimer la fonction GET_TICKET de GLPI_PAU
DROP FUNCTION GLPI_PAU.GET_TICKET;

-- Supprimer la procédure GET_USER_TICKETS de GLPI_PAU
DROP PROCEDURE GLPI_PAU.GET_USER_TICKETS;

-- Supprimer la procédure GET_TICKET_COMMENTS de GLPI_PAU
DROP PROCEDURE GLPI_PAU.GET_TICKET_COMMENTS;

-- Supprimer la procédure SET_TICKET_STATUS de GLPI_PAU
DROP PROCEDURE GLPI_PAU.SET_TICKET_STATUS;

-- Supprimer la procédure SOLVE_TICKET de GLPI_PAU
DROP PROCEDURE GLPI_PAU.SOLVE_TICKET;

-- Supprimer la procédure CLOSE_TICKET de GLPI_PAU
DROP PROCEDURE GLPI_PAU.CLOSE_TICKET;

-- Supprimer la procédure ASSIGN_TICKET_TO_USER de GLPI_PAU
DROP PROCEDURE GLPI_PAU.ASSIGN_TICKET_TO_USER;

-- Supprimer la procédure REFRESH_MATERIALIZED_VIEW de GLPI_PAU
DROP PROCEDURE GLPI_PAU.REFRESH_MATERIALIZED_VIEW;

COMMIT;
EXIT;
