CREATE DATABASE LINK 
GLPI_CERGY.LK_GLPI_PAU CONNECT TO glpi_pau_admin_1 IDENTIFIED BY your_password USING '127.0.0.1:1521';
CREATE DATABASE LINK 
GLPI_PAU.LK1_GLPI_CERGY CONNECT TO glpi_pau_admin_1 IDENTIFIED BY your_password USING '127.0.0.1:1521';

COMMIT;
EXIT;