ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--Creation TABLESPACES et SCHEMA GLPI_TEST
CREATE TABLESPACE GLPI_TEST_TABSPACE
datafile 'C:\TAD\GLPI_DB_TEST\GLPI_TEST_TABSPACE.dat'
SIZE 100M AUTOEXTEND ON;


CREATE TEMPORARY TABLESPACE GLPI_TEST_TABSPACE_TEMP
tempfile 'C:\TAD\GLPI_DB_TEST\GLPI_TEST_TABSPACE_TEMP.dat'
SIZE 50M AUTOEXTEND ON;

CREATE USER GLPI_TEST 
IDENTIFIED BY GLPI_TEST_PASSWORD
DEFAULT TABLESPACE GLPI_TEST_TABSPACE
TEMPORARY TABLESPACE GLPI_TEST_TABSPACE_TEMP;

GRANT CONNECT, CREATE SESSION TO GLPI_TEST;
GRANT DBA TO GLPI_TEST;

--Creation TABLESPACES et SCHEMA GLPI_PROD
CREATE TABLESPACE GLPI_PROD_TABSPACE
datafile 'C:\TAD\GLPI_DB_PROD\GLPI_PROD_TABSPACE.dat'
SIZE 100M AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE GLPI_PROD_TABSPACE_TEMP
tempfile 'C:\TAD\GLPI_DB_PROD\GLPI_PROD_TABSPACE_TEMP.dat'
SIZE 50M AUTOEXTEND ON;

CREATE USER GLPI_PROD 
IDENTIFIED BY GLPI_PROD_PASSWORD
DEFAULT TABLESPACE GLPI_PROD_TABSPACE
TEMPORARY TABLESPACE GLPI_PROD_TABSPACE_TEMP;

GRANT CONNECT, CREATE SESSION TO GLPI_PROD;
GRANT DBA TO GLPI_PROD;


-- -- Création du tablespace et du tablespace temporaire pour GLPI_OBSERVER
-- CREATE TABLESPACE GLPI_OBSERVER_TS DATAFILE 'C:\TAD\GLPI_ROLES\GLPI_OBSERVER_TS.dat' SIZE 100M AUTOEXTEND ON;
-- CREATE TEMPORARY TABLESPACE GLPI_OBSERVER_TEMP_TS TEMPFILE 'C:\TAD\GLPI_ROLES\GLPI_OBSERVER_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- -- Création du tablespace et du tablespace temporaire pour GLPI_ANALYST
-- CREATE TABLESPACE GLPI_ANALYST_TS DATAFILE 'C:\TAD\GLPI_ROLES\GLPI_ANALYST_TS.dat' SIZE 100M AUTOEXTEND ON;
-- CREATE TEMPORARY TABLESPACE GLPI_ANALYST_TEMP_TS TEMPFILE 'C:\TAD\GLPI_ROLES\GLPI_ANALYST_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- -- Création du tablespace et du tablespace temporaire pour GLPI_DEV
-- CREATE TABLESPACE GLPI_DEV_TS DATAFILE 'C:\TAD\GLPI_ROLES\GLPI_DEV_TS.dat' SIZE 100M AUTOEXTEND ON;
-- CREATE TEMPORARY TABLESPACE GLPI_DEV_TEMP_TS TEMPFILE 'C:\TAD\GLPI_ROLES\GLPI_DEV_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;

-- -- Création du tablespace et du tablespace temporaire pour GLPI_ADMIN
-- CREATE TABLESPACE GLPI_ADMIN_TS DATAFILE 'C:\TAD\GLPI_ROLES\GLPI_ADMIN_TS.dat' SIZE 100M AUTOEXTEND ON;
-- CREATE TEMPORARY TABLESPACE GLPI_ADMIN_TEMP_TS TEMPFILE 'C:\TAD\GLPI_ROLES\GLPI_ADMIN_TEMP_TS.dbf' SIZE 50M AUTOEXTEND ON;


COMMIT;
exit;