ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE CLUSTER GLPI_CERGY.user_cluster (user_id INT) TABLESPACE GLPI_CERGY_TABSPACE; 
CREATE CLUSTER GLPI_CERGY.ticket_cluster (ticket_id INT) TABLESPACE GLPI_CERGY_TABSPACE; 

CREATE CLUSTER GLPI_PAU.user_cluster (user_id INT) TABLESPACE GLPI_PAU_TABSPACE; 
CREATE CLUSTER GLPI_PAU.ticket_cluster (ticket_id INT) TABLESPACE GLPI_PAU_TABSPACE; 

COMMIT;
EXIT;
