-- Supprimer la fonction CHECK_DEPENDENCY
DROP FUNCTION GLPI_PROD.CHECK_VALUE_EXIST;
DROP FUNCTION GLPI_TEST.CHECK_VALUE_EXIST;

-- Supprimer la fonction GET_ID_WHERE   
DROP FUNCTION GLPI_PROD.GET_ID_WHERE;
DROP FUNCTION GLPI_TEST.GET_ID_WHERE;


COMMIT;
EXIT;
