DROP INDEX GLPI_PROD.idx_tickets_fk_user;
DROP INDEX GLPI_PROD.idx_tickets_creation_date;
DROP INDEX GLPI_PROD.idx_tickets_last_modification_date;
DROP INDEX GLPI_PROD.idx_tickets_resolution_date;
DROP INDEX GLPI_PROD.idx_tickets_closing_date;
DROP INDEX GLPI_PROD.idx_tickets_fk_priority;
DROP INDEX GLPI_PROD.idx_tickets_fk_location;
DROP INDEX GLPI_PROD.idx_comments_fk_ticket;
DROP INDEX GLPI_PROD.idx_comments_fk_user;
DROP INDEX GLPI_PROD.idx_users_fk_role;
DROP INDEX GLPI_PROD.idx_users_fk_group;
DROP INDEX GLPI_PROD.idx_tickets_fk_type;
DROP INDEX GLPI_PROD.idx_tickets_fk_status;
DROP INDEX GLPI_PROD.idx_tickets_fk_category;
DROP INDEX GLPI_PROD.idx_tickets_fk_assigned_group;
DROP INDEX GLPI_PROD.idx_tickets_status_priority;
DROP INDEX GLPI_PROD.idx_comments_user_creation_date;
DROP INDEX GLPI_PROD.idx_users_role_company;
DROP INDEX GLPI_PROD.idx_users_group_company;
DROP INDEX GLPI_PROD.idx_users_location_company;


DROP INDEX GLPI_TEST.idx_tickets_fk_user;
DROP INDEX GLPI_TEST.idx_tickets_creation_date;
DROP INDEX GLPI_TEST.idx_tickets_last_modification_date;
DROP INDEX GLPI_TEST.idx_tickets_resolution_date;
DROP INDEX GLPI_TEST.idx_tickets_closing_date;
DROP INDEX GLPI_TEST.idx_tickets_fk_priority;
DROP INDEX GLPI_TEST.idx_tickets_fk_location;
DROP INDEX GLPI_TEST.idx_comments_fk_ticket;
DROP INDEX GLPI_TEST.idx_comments_fk_user;
DROP INDEX GLPI_TEST.idx_users_fk_role;
DROP INDEX GLPI_TEST.idx_users_fk_group;
DROP INDEX GLPI_TEST.idx_tickets_fk_type;
DROP INDEX GLPI_TEST.idx_tickets_fk_status;
DROP INDEX GLPI_TEST.idx_tickets_fk_category;
DROP INDEX GLPI_TEST.idx_tickets_fk_assigned_group;
DROP INDEX GLPI_TEST.idx_tickets_status_priority;
DROP INDEX GLPI_TEST.idx_comments_user_creation_date;
DROP INDEX GLPI_TEST.idx_users_role_company;
DROP INDEX GLPI_TEST.idx_users_group_company;
DROP INDEX GLPI_TEST.idx_users_location_company;
COMMIT;
exit;