-- Supprimer la fonction CHECK_DEPENDENCY
DROP FUNCTION GLPI_CERGY.CHECK_VALUE_EXIST;
DROP FUNCTION GLPI_PAU.CHECK_VALUE_EXIST;

-- Supprimer la fonction GET_ID_WHERE   
DROP FUNCTION GLPI_CERGY.GET_ID_WHERE;
DROP FUNCTION GLPI_PAU.GET_ID_WHERE;


COMMIT;
EXIT;
